source 'https://rubygems.org'

ruby '>= 2.6.10'

gem 'cocoapods', '>= 1.13', '< 1.16'
gem 'activesupport', '>= 6.1.7.5', '< 7.1.0'
# Ruby 3.4 removed kconv from stdlib; provided by the nkf gem.
gem 'nkf'
