const fs = require('fs');
const { version } = require('../package.json');

fs.writeFileSync(
  `${__dirname}/../src/version.ts`,
  `// Generated by scripts/generate-version.js — do not edit manually.\nexport const version = '${version}';\n`
);
