name: Push release to NPM

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      NODE-VERSION: 20
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE-VERSION }}
          registry-url: https://registry.npmjs.org/
      - name: Build and publish to npm
        run: yarn install --frozen-lockfile
      - name: Upload artifacts
        run: |
          echo always-auth=true > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
