name: Push release to NPM

on:
  workflow_dispatch:
  push:
      tags:
        - '*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      NODE-VERSION: 20
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #4.4.0
        with:
          node-version: ${{ env.NODE-VERSION }}
          registry-url: https://registry.npmjs.org/
      - name: Build and publish to npm
        run: yarn install --frozen-lockfile
      - name: Upload artifacts
        run: |
          echo always-auth=true > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
